# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-30 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comunica7', '0004_productos_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadotareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tiempo_estimado', models.TimeField(blank=True, null=True)),
                ('costo', models.CharField(blank=True, max_length=1000, null=True)),
                ('revisado', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, max_length=1000, null=True)),
                ('estado', models.ForeignKey(blank=True, db_column='estado_tarea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comunica7.Estadotareas')),
            ],
            options={
                'verbose_name': 'Tareas / Incidencias',
                'managed': True,
            },
        ),
    ]
