# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-30 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunica7', '0005_estadotareas_programadores_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='programador',
            field=models.ForeignKey(blank=True, db_column='programador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comunica7.Programadores'),
        ),
    ]
