# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-27 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0105_auto_20181227_2154'),
        ('callcenter', '0100_auto_20181227_2152'),
    ]

    operations = [
    ]
