# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-30 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colasIN', '0048_auto_20190128_1623'),
        ('colasIN', '0048_auto_20190130_1116'),
    ]

    operations = [
    ]
