# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('orden', models.CharField(blank=True, max_length=100)),
                ('cliente', models.CharField(blank=True, max_length=100)),
                ('id_cliente', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
