# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180828_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='campania',
            field=models.ForeignKey(blank=True, db_column='campania', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Campania'),
        ),
    ]
