# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-06 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181006_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dblaster',
            old_name='evento',
            new_name='campania',
        ),
        migrations.AlterField(
            model_name='agente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 33, 40, 955955)),
        ),
        migrations.AlterField(
            model_name='api',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 33, 40, 953386)),
        ),
        migrations.AlterField(
            model_name='base',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 33, 40, 951013)),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 10, 6, 15, 33, 40, 948225)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 33, 40, 945368)),
        ),
        migrations.AlterField(
            model_name='dblaster',
            name='parametro_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Deuda'),
        ),
        migrations.AlterField(
            model_name='dblaster',
            name='parametro_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 33, 40, 947493)),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 33, 40, 944105)),
        ),
    ]
