# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-06 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181006_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 37, 41, 960317)),
        ),
        migrations.AlterField(
            model_name='api',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 37, 41, 959194)),
        ),
        migrations.AlterField(
            model_name='base',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 37, 41, 958119)),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 10, 6, 15, 37, 41, 956485)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 37, 41, 954763)),
        ),
        migrations.AlterField(
            model_name='dblaster',
            name='despedida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dblaster',
            name='dtmf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dblaster',
            name='respuesta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 37, 41, 955917)),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 37, 41, 953763)),
        ),
    ]
