# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180828_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='campania',
            name='fecha_cargada',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='usuario',
        ),
        migrations.AddField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 8, 28, 20, 1, 21, 831373)),
        ),
        migrations.AlterField(
            model_name='campania',
            name='archivo',
            field=models.FileField(upload_to='static'),
        ),
        migrations.AddField(
            model_name='campania',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
        ),
    ]
