# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-06 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181006_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 38, 31, 756106)),
        ),
        migrations.AlterField(
            model_name='api',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 38, 31, 754826)),
        ),
        migrations.AlterField(
            model_name='base',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 38, 31, 753597)),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 10, 6, 15, 38, 31, 751553)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 38, 31, 749651)),
        ),
        migrations.AlterField(
            model_name='dblaster',
            name='oc7_2',
            field=models.IntegerField(blank=True, db_column='OC7_2', null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 38, 31, 750908)),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 6, 15, 38, 31, 748792)),
        ),
    ]
