# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180828_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 8, 28, 20, 3, 14, 315572)),
        ),
    ]
