# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180828_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 8, 28, 20, 5, 12, 333611)),
        ),
    ]
