# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180828_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='campania',
            name='estado',
            field=models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estado'),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 8, 28, 20, 6, 9, 670927)),
        ),
    ]
