# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180828_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campania',
            name='acd',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='canales',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='discado',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='grabacion',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='hombreobjetivo',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='htfin',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='htinicio',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='inactividad',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='llamadaxhora',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='mxllamada',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='o_error_cnt',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='o_nocontesto_cnt',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='password',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='prefijo',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='status',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='t1',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='t2',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='t3',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='tgestion',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='timbrado1',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='timbrado2',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='timbrados',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='troncal',
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 8, 28, 20, 16, 45, 731056)),
        ),
        migrations.AlterField(
            model_name='campania',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
