# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 20:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180828_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='base',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='base',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='base',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='base',
            name='telefono',
        ),
        migrations.AddField(
            model_name='base',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='deuda_pendiente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='dni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='importe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='telefono_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='base',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 8, 28, 20, 30, 38, 334965)),
        ),
    ]
