# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 21:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20180828_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agentes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anexo', models.IntegerField(blank=True, null=True)),
                ('fono', models.IntegerField(blank=True, null=True)),
                ('tiempo', models.DateTimeField(blank=True, null=True)),
                ('destino', models.IntegerField(blank=True, null=True)),
                ('duracion', models.TimeField(blank=True, null=True)),
                ('atendidas', models.IntegerField(blank=True, null=True)),
                ('contactadas', models.IntegerField(blank=True, null=True)),
                ('est_ag_predictivo', models.IntegerField(blank=True, null=True)),
                ('canal', models.CharField(blank=True, max_length=100)),
                ('disponible', models.IntegerField(blank=True, null=True)),
                ('tiniciogestion', models.DateTimeField(blank=True, null=True)),
                ('tfingestion', models.DateTimeField(blank=True, null=True)),
                ('tiniciollamada', models.DateTimeField(blank=True, null=True)),
                ('tfinllamada', models.DateTimeField(blank=True, null=True)),
                ('tinicioespera', models.DateTimeField(blank=True, null=True)),
                ('tfinespera', models.DateTimeField(blank=True, null=True)),
                ('tiniciotipeo', models.DateTimeField(blank=True, null=True)),
                ('wordstipeo', models.IntegerField(blank=True, null=True)),
                ('tiniciopausa', models.DateTimeField(blank=True, null=True)),
                ('checa', models.CharField(blank=True, max_length=100)),
                ('checabreak', models.CharField(blank=True, max_length=100)),
                ('tiniciobreak', models.DateTimeField(blank=True, null=True)),
                ('checaser', models.CharField(blank=True, max_length=100)),
                ('tinicioservicio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estado')),
                ('supervisor', models.ForeignKey(blank=True, db_column='supervisor', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Supervisor')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 8, 28, 21, 41, 8, 18184)),
        ),
    ]
