# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180828_2141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agentes',
            new_name='Agente',
        ),
        migrations.AlterModelOptions(
            name='agente',
            options={'verbose_name': 'Agente'},
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 8, 28, 21, 44, 32, 375951)),
        ),
    ]
