# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180828_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='checa',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='checabreak',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='checaser',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='tfinespera',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='tfingestion',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='tfinllamada',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='tiniciobreak',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='tinicioespera',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='tiniciogestion',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='tiniciollamada',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='tiniciopausa',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='tinicioservicio',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='tiniciotipeo',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='wordstipeo',
        ),
        migrations.AlterField(
            model_name='agente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 8, 28, 21, 45, 57, 452128)),
        ),
    ]
