# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-28 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180828_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 8, 28, 21, 47, 53, 37902)),
        ),
        migrations.AddField(
            model_name='base',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 8, 28, 21, 47, 53, 35819)),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 8, 28, 21, 47, 53, 31033)),
        ),
        migrations.AddField(
            model_name='estado',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 8, 28, 21, 47, 53, 32155)),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 8, 28, 21, 47, 53, 28927)),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 8, 28, 21, 47, 53, 33134)),
        ),
    ]
