# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-05 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181005_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadocampania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='agente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 5, 15, 58, 25, 865376)),
        ),
        migrations.AlterField(
            model_name='api',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 5, 15, 58, 25, 864032)),
        ),
        migrations.AlterField(
            model_name='base',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 5, 15, 58, 25, 862868)),
        ),
        migrations.AlterField(
            model_name='campania',
            name='estado',
            field=models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estadocampania'),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(db_column='fecha cargada', default=datetime.datetime(2018, 10, 5, 15, 58, 25, 860979)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 5, 15, 58, 25, 858566)),
        ),
        migrations.AlterField(
            model_name='estado',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 5, 15, 58, 25, 860312)),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 10, 5, 15, 58, 25, 857455)),
        ),
    ]
