# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-27 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0097_auto_20181227_1652'),
        ('speech', '0095_auto_20181227_1706'),
    ]

    operations = [
    ]
