# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-19 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreproveedor',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='peso_subresultado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
