# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='peso_id_gestion',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='score',
            name='peso_resultado',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='score',
            name='peso_tipo_gestion',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
