# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreproveedor',
            name='cartera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Cartera'),
        ),
    ]
