# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-19 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0002_auto_20181218_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='peso',
            new_name='peso_subresultado',
        ),
    ]
