# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-19 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0002_auto_20181219_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='peso',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='peso_subresultado',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
