# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0002_cuadrante_plano_producto_tipo_cartera_ubigeo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentas',
            name='Proveedor',
        ),
        migrations.AddField(
            model_name='cuentas',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_proveedor', to='discador.Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cartera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartera', to='discador.Cartera'),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='cartera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_cartera', to='discador.Cartera'),
        ),
    ]
