# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0002_auto_20181218_1947'),
        ('discador', '0002_auto_20181218_1922'),
    ]

    operations = [
    ]
