# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0003_auto_20181116_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='cartera',
        ),
        migrations.AddField(
            model_name='cartera',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Proveedor'),
        ),
    ]
