# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0003_auto_20181219_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentas',
            old_name='capital',
            new_name='ciclo',
        ),
        migrations.RenameField(
            model_name='cuentas',
            old_name='compania',
            new_name='fecha_prox_pago',
        ),
        migrations.RenameField(
            model_name='cuentas',
            old_name='interes',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='cuentas',
            old_name='mora',
            new_name='id_gestor',
        ),
        migrations.RenameField(
            model_name='cuentas',
            old_name='total',
            new_name='idcliente',
        ),
        migrations.RemoveField(
            model_name='cuentas',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='cuentas',
            name='fecha_concecion',
            field=models.DateField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='fecha_deuda',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='imp_cap_original',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='imp_capital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='imp_compania',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='imp_descuento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='imp_interes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='imp_minimo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='imp_mora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='imp_otros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='imp_prox_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='imp_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='imp_vencido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='moneda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='nro_tarjeta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='nuemero_cuotas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='observacion01',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='observacion02',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='observacion03',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='rango_dias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='segmento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='tipo_clasificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='tipo_credito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
