# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0004_auto_20181219_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='fecha_concecion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='fecha_vencimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
