# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0005_auto_20181220_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentas',
            old_name='imp_compania',
            new_name='imp_campania',
        ),
    ]
