# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0006_auto_20181220_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='fecha_deuda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
