# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0007_auto_20181220_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='discador.Telefonos'),
        ),
        migrations.AlterField(
            model_name='telefonos',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
