# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-31 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0009_auto_20190128_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agente',
            options={'verbose_name_plural': 'Agentes'},
        ),
    ]
