# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0010_auto_20181126_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='sub_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categoria', to='discador.Sub_categoria'),
        ),
    ]
