# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0015_score_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='estado',
            field=models.BooleanField(default=0),
        ),
    ]
