# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-07 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0017_auto_20181207_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='estado',
            field=models.BooleanField(default=0),
        ),
    ]
