# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-12 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0021_auto_20181212_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_categoria',
            new_name='Subresultado',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='sub_categoria',
            new_name='subresultado',
        ),
    ]
