# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-14 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0023_merge_20181213_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteraproveedor',
            name='cartera',
        ),
        migrations.RemoveField(
            model_name='carteraproveedor',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='proveedorcarteras',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Negocio'),
        ),
        migrations.DeleteModel(
            name='CarteraProveedor',
        ),
    ]
