# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0024_auto_20181214_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='cartera',
        ),
        migrations.RemoveField(
            model_name='score',
            name='proveedor',
        ),
    ]
