# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-17 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0024_auto_20181214_1551'),
        ('discador', '0024_auto_20181214_0601'),
    ]

    operations = [
    ]
