# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0026_scoreproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreproveedor',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Score'),
        ),
    ]
